--liquibase formatted sql

--changeset menejek:1
CREATE TABLE loan_application (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                  application_id UUID NOT NULL,
                                  created_at TIMESTAMP(6) NOT NULL,
                                  idempotency_key UUID NOT NULL,
                                  monthly_count INTEGER NOT NULL,
                                  monthly_payment NUMERIC(38, 2) NOT NULL,
                                  status VARCHAR(255) CHECK (status IN (
                                                                        'UNDER_REVIEW',
                                                                        'APPROVED',
                                                                        'REJECTED',
                                                                        'DOCUMENTS_PENDING',
                                                                        'NEEDS_MANUAL_REVIEW'
                                      )),
                                  total_credit NUMERIC(38, 2) NOT NULL,
                                  updated_at TIMESTAMP(6),
                                  yearly_interest_rate NUMERIC(38, 2) NOT NULL,

                                  PRIMARY KEY (id)
);