spring.application.name=LoanCalculatorService
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5433/loan_db
spring.datasource.username=admin
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect